### ISSUE TITLE
Remove deprecated input field

### ISSUE THREAD

**Issue by martinglova** [kamilkisiela/graphql-inspector#2102]
**Describe the bug**

Not being able to remove deprecated input field. `deprecated` reason is ignored for `input` type.

**To Reproduce**
When I create input as:

```
input Foo {
  a: String
  b: String
  c: String @deprecated(reason: "Can be removed, but clients must be updated too")
}
```

I'm not able to remove deprecated `Foo.c` from the input - it's breaking change even when using `suppressRemovalOfDeprecatedField` rule.

**Expected behavior**

I should be able to remove deprecated input field when using `suppressRemovalOfDeprecatedField` rule. It should be considered as `Dangerous` change instead of `Breaking`.

**Environment:**

- OS: `macOS (12.3.1)`
- `@graphql-inspector/cli`: `3.1.2`
- `graphql`: `16.0.0`
- NodeJS: `v17.8.0`

**Additional context**

I've created a fork with the fix, please see the commit: https://github.com/martinglova/graphql-inspector/commit/bc27f6b47700dd6f005f82c170891db3a5ce7321 and Pull request: https://github.com/kamilkisiela/graphql-inspector/pull/2103

**Comment by ppease** [comment]
Just to pile on with this we also have a need for this feature.  In particular we care about deprecated fields being reported on input types in general.  I think this was something added fairly recently to the graphQL spec. I think PR 2103 would solve that problem too since it is updating the utility function that identifies deprecated fields.

**Comment by martinglova** [comment]
@kamilkisiela could you please take a look? It's a very similar issue to [Removal of deprecated enum values](https://github.com/kamilkisiela/graphql-inspector/pull/1829).
