### ISSUE TITLE
Require a Node Version above 8.10.0 otherwise it crashes

### ISSUE THREAD

**Issue by MrDesjardins** [kamilkisiela/graphql-inspector#234]
I am getting the following error when trying to install the `api` package.

> pdesjardins @ ~/code/graphqlinspector/packages/api * master
 [23] → yarn install
yarn install v1.7.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error @probot/serverless-lambda@0.3.0: The engine "node" is incompatible with this module. Expected version ">= 8.10.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

I would suggest to use `nvm` and have the `.nvm` file pointing to the expected NodeJS. 10.15.3 works with few warnings.

**Comment by kamilkisiela** [comment]
The `/api` and `/ui` are there but it's just to encourage people to help and build something out of it, a starting point.

I don't think that including `.nvm` is a must-have here, when you see `node >= 8.10.0` is required, you just `nvm use 8` and done. What is the issue here?

The v8 seems to be in maintenance: https://nodejs.org/en/about/releases/

**Comment by MrDesjardins** [comment]
The issue is that to get started with this project you stumble into quite a few warning and error. It would be a greater experience to future contributor to have the project setup in a way that you do not need to get into trouble to discover what is required. 

I personally gave up because I couldn't make it works locally within a reasonable time frame. If you see no problem, feel free discard my feedback and close the issue. Have a good day.

**Comment by kamilkisiela** [comment]
I will leaveI think `engine` in `package.json` is enough
