### ISSUE TITLE
validate doesn't work when fragments are stored in another file

### ISSUE THREAD

**Issue by benasher44** [kamilkisiela/graphql-inspector#2657]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
     > Make sure to fork this template and run `pnpm generate` in the terminal.
     >
     > Please make sure the Codegen and plugins version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

Running `graphql-inspector validate './documents/**/*.graphql' './schema.graphql'` fails with:

"Error: Couldn't find type MyFragment in any of the schemas"

The issue seems to be that validate considers each document individually, rather than attempt to combine them (or similar) prior to validating. `@graphql-codegen` has no issue with this setup where we have a fragments.graphql file where the shared fragments live, and then any graphql document might use one of those fragments.

**To Reproduce** Steps to reproduce the behavior:

1. Create a graphql schema
2. Create a documents such that fragments are stored separately from the documents using them and such that fragments aren't necessarily loaded first.

**Expected behavior**

It loads the documents for validation.

**Environment:**

- OS: macOS 14.1
- `@graphql-inspector/...`: 4.0.2
- `graphql`: 16.8.1
- NodeJS: 18.18.2

**Additional context**

**Comment by Urigo** [comment]
Thank you @benasher44 for reporting!

Can you please create a reproduction on CodeSandbox?

I'm labeling this issue according to our new Contribution Guide and [issue flow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow) `stage 0`.

Now in order to advance to `stage 1` we'll need a simple reproduction, maybe in code-sandbox? 

Later to progress to `stage 2`, a failing test would be needed, would be great if someone could help progress the issues through the [stages](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow).

Thank you and sorry that this comment is not a complete solution (yet).

**Comment by benasher44** [comment]
After trying to make a repro, I figured out that our project had incorrect `# import` lines that were confusing the loader. Removing all of those fixed it!
