### ISSUE TITLE
Is Inspector's Diff similar to GraphQL's findBreakingChanges?

### ISSUE THREAD

**Issue by shavo007** [kamilkisiela/graphql-inspector#702]
hi,

is this similar logic to graphql lib?
https://github.com/graphql/graphql-js/blob/master/src/utilities/findBreakingChanges.js

thanks,
shane

**Comment by kamilkisiela** [comment]
@shavo007 Inspector's schema diff shows all differences - breaking, dangerous and totally safe.

In `graphql-js` there are two functions: `findBreakingChanges` and `findDangerousChanges`.
Both cover pretty much what GraphQL Inspector shows as breaking and dangerous but Inspector also shows you those non-breaking and non-dangerous changes, so it gives you a full insight.

Why I decided to move away from `graphql-js` is because it doesn't show which type / directive has changed, it contains only description and the kind of modification.

In `graphql-js` I get:

```js
{
  description: 'User.name was removed.',
  type: 'FIELD_REMOVED'
}
```

In GraphQL Inspector I have:

```js
{
  message: 'Directive @entity was removed',
  path: 'User.name',
  type: 'FIELD_REMOVED',
  criticality: {
    level: 'Breaking',
    reason: 'Removing a deprecated field is a breaking change. Before removing it, you may want to look at the field's usage to see the impact of removing the field.'
  }
}
```

I know I could use regex to extract types and directives from a description but it doesn't seem stable.

By owning the "diff" part I can introduce flags to mark a breaking change as only dangerous. Even more, I can decide which change is breaking or safe based on GraphQL Operations in an application or the acutal usage of GraphQL API (which fields were used in recent 30 days - if the one we want to remove was untouched since 2017, it's safe to remove it).

**Comment by shavo007** [comment]
thanks for the detailed explanation @kamilkisiela
