### ISSUE TITLE
Adding member to Union is a breaking change?

### ISSUE THREAD

**Issue by chrisae** [kamilkisiela/graphql-inspector#935]
Hi there,

I'm not 100% sure but I expected not, that adding new members to a union is a breaking change.

Simple example.

Before change:
```
union ChangesPayload = NameChanges | DateChanges

type NameChanges {
  change: SomeType
}

type DateChanges {
  changes: SomeType
}
```

After change, adding one more type:
```
union ChangesPayload = NameChanges | DateChanges | LocationChange

type NameChanges {
  change: SomeType
}

type DateChanges {
  changes: SomeType
}

type LocationChange {
  changes: SomeType
}
```

Gives this error:
```
UNION_MEMBER_ADDED Member 'LocationChange' was added to Union type 'ChangesPayload' ChangesPayload
```

The union becomes more general but it won't break the existing implementation. Or I'm missing something here?

Thanks for your help

**Comment by zionts** [comment]
I understand why adding a member to a union _could_ be a breaking change, and this is because client code may be relying on the fact that it has complete coverage of all of a union's cases. However, I agree with @chrisae that without understanding the kind of queries people are making, the default behavior should be to accept additions to unions, since existing queries will certainly continue to be executable, though the expectations that the client is relying upon may be violated. 

A similar product (Apollo Graph Manager) treats type additions to unions [as allowed changes](https://www.apollographql.com/docs/graph-manager/schema-validation/#non-breaking-changes). I think in general, it would be useful for the community to come together around a single set of these kinds of changes. That way, clients can have a clear understanding of _what_ they should be relying upon rather than potentially lacking consensus across client / server around what kinds of changes are safe.

**Comment by kamilkisiela** [comment]
950fb22 should fix it

**Comment by kamilkisiela** [comment]
[`v1.27.0`](https://github.com/kamilkisiela/graphql-inspector/releases/tag/v1.27.0)
